# site settings
title: Unpollute
email: jkim116@student.hbuhsd.edu
description: Mission Statement</br>To spread truths and facts of pollution and make people behave to protect the environment.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.unpollute.ga"# the base hostname & protocol for your site
# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings
#500px_url:
#facebook_url:
#github_url:
#gitlab_url: https://gitlab.com/unpollute/unpollute.github.io
#googleplus_url: https://plus.google.com/u/0/+AndrewBanchich
#instagram_url: https://instagram.com
#linkedin_url: https://www.linkedin.com/in/andrew-banchich-a4ba1195
#pinterest_url:
#sack_url:
#twitter_url: https://twitter.com/andrewbanchich

# build settings
markdown: kramdown

sass:
  style: compressed
